# Generated by Django 3.2.16 on 2022-11-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.DateField(verbose_name='show date'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='time',
            field=models.TimeField(verbose_name='show time'),
        ),
    ]
